sudo: required
dist: xenial

os: linux

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - axel
    - cpanminus
    - libluajit-5.1-dev
    - libgd-dev
    - libpcre3-dev

cache:
  apt: true

env:
  global:
    - LUAJIT_LIB=/usr/lib64/libluajit-5.1.so
    - LUAJIT_INC=/usr/include/luajit-2.0
    - LUA_INCLUDE_DIR=/usr/include/luajit-2.0
    - LUA_CMODULE_DIR=/lib
  matrix:
    - NGINX_VERSION=1.11.2
    - NGINX_VERSION=1.17.8
    
before_install:
  - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
  
install:
  - git clone https://github.com/openresty/openresty.git ../openresty
  - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx
  - git clone https://github.com/openresty/nginx-devel-utils.git
  - git clone https://github.com/openresty/lua-nginx-module.git ../lua-nginx-module
  - git clone https://github.com/openresty/echo-nginx-module.git ../echo-nginx-module
  - git clone https://github.com/simpl/ngx_devel_kit.git ../ndk-nginx-module
  - git clone https://github.com/openresty/sregex.git
  
script:
  - cd sregex && sudo make PREFIX=/usr install && cd ..
  - export PATH=$PWD/work/nginx/sbin:$PWD/nginx-devel-utils:$PATH
  - sh util/build.sh $NGINX_VERSION > build.log 2>&1 || (cat build.log && exit 1)
  - nginx -V
  - prove -r t
